/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import javax.crypto.*;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

/**
 *
 * @author omega
 */
public class PanelCodigo extends javax.swing.JPanel {
    ObjectOutputStream oos;
    ObjectInputStream ois;
    SecretKey key;
    JPanel content;
    /**
     * Creates new form PanelCodigo
     */
    public PanelCodigo(ObjectInputStream ois, ObjectOutputStream oos, SecretKey key, JPanel content) {
        initComponents();
        this.ois = ois;
        this.oos = oos;
        this.content = content;
        this.key = key;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        botonEnviar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CODIGO DE SEGURIDAD");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 50));

        codigoField.setBackground(new java.awt.Color(204, 204, 204));
        codigoField.setForeground(new java.awt.Color(0, 0, 0));
        codigoField.setBorder(null);
        add(codigoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 290, 30));

        botonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEnviarMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENVIAR");

        javax.swing.GroupLayout botonEnviarLayout = new javax.swing.GroupLayout(botonEnviar);
        botonEnviar.setLayout(botonEnviarLayout);
        botonEnviarLayout.setHorizontalGroup(
            botonEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonEnviarLayout.setVerticalGroup(
            botonEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(botonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 160, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEnviarMousePressed
        try {
            //comprovamos que nos pase un codigo
            if (!codigoField.getText().isBlank()) {
                //enviamos el codigo
                Cipher desCipher = Cipher.getInstance("DES");
                desCipher.init(Cipher.ENCRYPT_MODE, key);
                byte[] codigoCifrado = desCipher.doFinal(codigoField.getText().getBytes());
                oos.writeObject(codigoCifrado);
                //recogemos la respuesta de si el codigo es correcto
                if ((boolean) ois.readObject()) {
                    JOptionPane.showMessageDialog(null, "Numero correcto, iniciando transferencia.");
                } else {
                    JOptionPane.showMessageDialog(null, "Numero incorrecto operacion cancelada.");
                }
                PanelNuevaTranferencia frame = new PanelNuevaTranferencia(ois, oos, key, content);
                frame.setSize(830, 550);
                frame.setLocation(0, 0);
                content.removeAll();
                content.add(frame, BorderLayout.CENTER);
                content.revalidate();
                content.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "El campo del codigo tiene que estar rellenado.");
            }
        } catch (NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException | IOException ex) {
            JOptionPane.showMessageDialog(null, "ERROR inesperado.");
            ex.printStackTrace();
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo.");
        } catch (InvalidKeyException ex) {
            JOptionPane.showMessageDialog(null, "La llave usada no es la correcta.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido encontrar la clase para el casteo.");
        }
    }//GEN-LAST:event_botonEnviarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonEnviar;
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
