/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import javax.crypto.*;
import javax.swing.*;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author omega
 */
public class PanelNuevaCuenta extends javax.swing.JPanel {
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private SecretKey key;
    /**
     * Creates new form PanelNuevaCuenta
     */
    public PanelNuevaCuenta(ObjectInputStream ois, ObjectOutputStream oos, SecretKey key) {
        initComponents();
        this.ois = ois;
        this.oos = oos;
        this.key = key;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonAnadir1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVA CUENTA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Numero de  cuenta ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 370, 20));

        numeroField.setBackground(new java.awt.Color(204, 204, 204));
        numeroField.setBorder(null);
        add(numeroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 300, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 300, -1));

        botonAnadir1.setBackground(new java.awt.Color(57, 57, 58));
        botonAnadir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAnadir1MousePressed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(219, 219, 219));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Añadir Cuenta");

        javax.swing.GroupLayout botonAnadir1Layout = new javax.swing.GroupLayout(botonAnadir1);
        botonAnadir1.setLayout(botonAnadir1Layout);
        botonAnadir1Layout.setHorizontalGroup(
            botonAnadir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonAnadir1Layout.setVerticalGroup(
            botonAnadir1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(botonAnadir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadir1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadir1MousePressed
        try {
            //configuranmos el pattern de la cuenta y comprovamos los campos
            Pattern pattern  = Pattern.compile("^([A-Za-z]{2}[0-9]{2} [0-9]{4} [0-9]{2} [0-9]{10})$");
            Matcher ncuenta = pattern.matcher(numeroField.getText());
            if (!numeroField.getText().isBlank() && ncuenta.find()) {
                //mandamos la opcion que hemos elegido
                oos.writeObject(2);
                Cipher desCipher = Cipher.getInstance("DES");
                desCipher.init(Cipher.ENCRYPT_MODE, key);
                byte[] nencriptado = desCipher.doFinal(numeroField.getText().getBytes());
                //mandamos la cuenta que queremos añadir y recuperamos la comprovacion
                oos.writeObject(nencriptado);
                if ((boolean) ois.readObject()) {
                    JOptionPane.showMessageDialog(null, "EL numero de cuenta se ha creado correctamente.");
                } else {
                    JOptionPane.showMessageDialog(null, "El numero de cuenta ya existe, usa otro.");
                    numeroField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El numero de cuenta esta mal escrito o vacio.");
            }
        } catch (IOException | NoSuchPaddingException | BadPaddingException | IllegalBlockSizeException ex) {
            JOptionPane.showMessageDialog(null, "ERROR inesperado.");
        } catch (NoSuchAlgorithmException ex) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo.");
        } catch (InvalidKeyException ex) {
            JOptionPane.showMessageDialog(null, "La llave no es la correcta.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos por que no se han podido castear.");
        }
    }//GEN-LAST:event_botonAnadir1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonAnadir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField numeroField;
    // End of variables declaration//GEN-END:variables
}
