/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import javax.crypto.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import clases.Cuenta;
import scrollbar.ScrollBarCustom;
import table.TableHeader;


/**
 * @author omega
 */
public class PanelCuentas extends javax.swing.JPanel {
    String[] nombreColumnas = {"id", "Nombre", "Telefono", "Email"};
    private SecretKey key;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;

    /**
     * Creates new form PanelClientes
     */
    public PanelCuentas(ObjectInputStream ois, ObjectOutputStream oos, SecretKey key) {
        this.key = key;
        this.oos = oos;
        this.ois = ois;
        initComponents();
        //cargamos el estilo de la tabla
        table1.setShowHorizontalLines(true);
        table1.setGridColor(new Color(230, 230, 230));
        table1.setRowHeight(30);
        table1.getTableHeader().setReorderingAllowed(true);
        table1.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader header = new TableHeader(value + "");
                if (column == nombreColumnas.length) {
                    header.setHorizontalAlignment(JLabel.CENTER);
                }
                return header;
            }
        });
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
        fixtable(jScrollPane1);
        //cargamos los datos
        modificarTabla();
    }

    public void fixtable(JScrollPane scroll) {
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    public void modificarTabla() {
        try {
            //mandamos la opcion que queremos
            oos.writeObject(1);
            Cipher desCipher = Cipher.getInstance("DES");
            desCipher.init(Cipher.DECRYPT_MODE, key);
            //recuperamos la lista de cuentas del usuario encriptadas
            byte[] cuentasCifradas = (byte[]) ois.readObject();
            byte[] cuentasBytes = desCipher.doFinal(cuentasCifradas);
            ByteArrayInputStream bis = new ByteArrayInputStream(cuentasBytes);
            ObjectInputStream oisbytes = new ObjectInputStream(bis);
            List<Cuenta> cuentas = (List<Cuenta>) oisbytes.readObject();
            bis.close();
            oisbytes.close();
            //cargamos las cuentas en la tabla para mostrarlas
            int cantidad = cuentas.size();
            String[][] d = new String[cantidad][2];
            String[] nombreColumnas = {"Numero de cuenta", "Saldo"};
            for (int i = 0; i < cuentas.size(); i++) {
                d[i][0] = String.valueOf(cuentas.get(i).getNumero());
                d[i][1] = String.valueOf(cuentas.get(i).getSaldo());
            }
            table1.setModel(new DefaultTableModel(d, nombreColumnas));
        } catch (IOException | BadPaddingException | IllegalBlockSizeException | NoSuchPaddingException e) {
            JOptionPane.showMessageDialog(null, "ERROR inesperado.");
        } catch (NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo.");
        } catch (InvalidKeyException e) {
            JOptionPane.showMessageDialog(null, "La llave no es la correcta.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos por que no se pueden castear.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )
    );
    jScrollPane1.setViewportView(table1);

    add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 690, 400));

    jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(0, 0, 0));
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("GESTION DE CUENTAS");
    add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
