/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import clases.User;

import javax.crypto.*;
import javax.swing.*;
import java.io.*;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * @author omega
 */
public class VentanaLogin extends javax.swing.JFrame {
    private Cipher cipher;
    private ObjectOutputStream oos;
    private ObjectInputStream ois;
    private SecretKey key;

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin(ObjectInputStream ois, ObjectOutputStream oos, SecretKey key) {
        initComponents();
        this.ois = ois;
        this.oos = oos;
        this.key = key;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contrasenaField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        userField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        contrasenaField.setBackground(new java.awt.Color(204, 204, 204));
        contrasenaField.setBorder(null);
        jPanel1.add(contrasenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 230, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 230, 10));

        userField.setBackground(new java.awt.Color(204, 204, 204));
        userField.setBorder(null);
        jPanel1.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        botonIniciar.setBackground(new java.awt.Color(57, 57, 58));
        botonIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIniciarMousePressed(evt);
            }
        });
        botonIniciar.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(219, 219, 219));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Iniciar Sesion");
        botonIniciar.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 200, 50));

        botonRegistrarse.setBackground(new java.awt.Color(57, 57, 58));
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistrarseMousePressed(evt);
            }
        });
        botonRegistrarse.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(219, 219, 219));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registrarse");
        botonRegistrarse.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 200, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarMousePressed
        //comprovamos que los campos tienen datos
        if (!userField.getText().isBlank() && !contrasenaField.getText().isBlank()) {
            try {
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                ObjectOutputStream oosbytes = new ObjectOutputStream(bos);
                oos.writeObject(1);
                //hasheamos la contraseña
                MessageDigest md = MessageDigest.getInstance("SHA");
                byte[] contrasenaBytes = contrasenaField.getText().getBytes();
                md.update(contrasenaBytes);
                byte[] resumen = md.digest();
                String hashContrasena = new String(resumen);
                //creamos un objeto con todos los datos del inicio de sesion
                User user = new User(userField.getText(), hashContrasena);
                //lo comvertimos a bytes
                oosbytes.writeObject(user);
                oosbytes.flush();
                byte[] userbytes = bos.toByteArray();
                //recogemos la clave
                cipher = Cipher.getInstance("DES");
                //configuramos modo encriptar
                cipher.init(Cipher.ENCRYPT_MODE, key);
                byte[] userCifrado = cipher.doFinal(userbytes);
                //enviamos objeto cifrado
                oos.writeObject(userCifrado);
                //recogemos login
                cipher.init(Cipher.DECRYPT_MODE, key);
                userCifrado = (byte[]) ois.readObject();
                userbytes = cipher.doFinal(userCifrado);
                ByteArrayInputStream bis = new ByteArrayInputStream(userbytes);
                ObjectInputStream oisbytes = new ObjectInputStream(bis);
                user = (User) oisbytes.readObject();
                bis.close();
                oisbytes.close();
                if (user.isAcierto()) {
                    JFrame frame = new VentanaPrincipal(ois, oos, key);
                    frame.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos vuelve a intentarlo.");
                }
            } catch (IOException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Ha surgido un error con el servidor intentalo mas tarde.");
                ex.printStackTrace();
            } catch (NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                JOptionPane.showMessageDialog(null, "ERROR inesperado.");
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo de encriptacion.");
            } catch (InvalidKeyException ex) {
                JOptionPane.showMessageDialog(null, "La llave no es correcta.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR tienes que rellenar todos los campos.");
        }
    }//GEN-LAST:event_botonIniciarMousePressed

    private void botonRegistrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMousePressed
        VentanaRegistrarse frame = new VentanaRegistrarse(ois, oos, key);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegistrarseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    int PUERTO = 5050;
                    String HOST = "localhost";
                    Socket socket = new Socket(HOST, PUERTO);
                    ObjectOutputStream oos = new ObjectOutputStream(socket.getOutputStream());
                    ObjectInputStream ois = new ObjectInputStream(socket.getInputStream());
                    SecretKey key = (SecretKey) ois.readObject();
                    new VentanaLogin(ois, oos, key).setVisible(true);
                } catch (UnknownHostException e) {
                    JOptionPane.showMessageDialog(null, "Ha surgido un error inesperado intentalo mas tarde.");
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, "Ha surgido un error al intentar conectarse con el servidor intentalo mas tarde.");
                } catch (ClassNotFoundException e) {
                    JOptionPane.showMessageDialog(null, "No se ha podido cargar la ventana de inicio de sesion.");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonIniciar;
    private javax.swing.JPanel botonRegistrarse;
    private javax.swing.JPasswordField contrasenaField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
