/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import clases.NuevoUsuario;

import javax.crypto.*;
import javax.swing.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author omega
 */
public class VentanaRegistrarse extends javax.swing.JFrame {
    private ObjectInputStream ois;
    private ObjectOutputStream oos;
    private SecretKey key;
    private boolean check;
    /**
     * Creates new form VentanaRegistrarse
     */
    public VentanaRegistrarse(ObjectInputStream ois, ObjectOutputStream oos, SecretKey key) {
        initComponents();
        this.ois = ois;
        this.oos = oos;
        this.key = key;

        try {
            oos.writeObject(3);
            PublicKey clavepub = (PublicKey) ois.readObject();
            byte[] firma = (byte[]) ois.readObject();
            Signature verificarsa = Signature.getInstance("SHA1WITHRSA");
            verificarsa.initVerify(clavepub);
            check = verificarsa.verify(firma);
            if (check) {
                JOptionPane.showMessageDialog(null, "El documento esta firmado digitalmente correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "El documento firmado no concide.");
            }
        } catch (IOException | SignatureException | NoSuchAlgorithmException e) {
            JOptionPane.showMessageDialog(null, "ERROR inesperado.");
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos por que no se pueden castear.");
        } catch (InvalidKeyException e) {
            JOptionPane.showMessageDialog(null, "La llave que se esta usando no¡ es la correcta.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        apellidoField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        edadField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        usuarioField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        botonRegistrarse = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        checkTerminos = new javax.swing.JCheckBox();
        contrasenaField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRARSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, -1));

        nombreField.setBackground(new java.awt.Color(204, 204, 204));
        nombreField.setBorder(null);
        jPanel1.add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 240, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 240, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 100, -1));

        apellidoField.setBackground(new java.awt.Color(204, 204, 204));
        apellidoField.setBorder(null);
        jPanel1.add(apellidoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 250, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 250, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 60, -1));

        edadField.setBackground(new java.awt.Color(204, 204, 204));
        edadField.setBorder(null);
        jPanel1.add(edadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 240, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 240, 10));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 100, -1));

        emailField.setBackground(new java.awt.Color(204, 204, 204));
        emailField.setBorder(null);
        jPanel1.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 250, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 250, 10));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, -1));

        usuarioField.setBackground(new java.awt.Color(204, 204, 204));
        usuarioField.setBorder(null);
        jPanel1.add(usuarioField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 240, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 240, 10));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 250, 10));

        botonRegistrarse.setBackground(new java.awt.Color(57, 57, 58));
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistrarseMousePressed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(219, 219, 219));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTRARSE");

        javax.swing.GroupLayout botonRegistrarseLayout = new javax.swing.GroupLayout(botonRegistrarse);
        botonRegistrarse.setLayout(botonRegistrarseLayout);
        botonRegistrarseLayout.setHorizontalGroup(
            botonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonRegistrarseLayout.setVerticalGroup(
            botonRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(botonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 160, 50));

        botonCancelar.setBackground(new java.awt.Color(57, 57, 58));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(219, 219, 219));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CANCELAR");

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 160, 50));

        checkTerminos.setBackground(new java.awt.Color(204, 204, 204));
        checkTerminos.setForeground(new java.awt.Color(0, 0, 0));
        checkTerminos.setText("Accepto los terminos");
        jPanel1.add(checkTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        contrasenaField.setBackground(new java.awt.Color(204, 204, 204));
        contrasenaField.setBorder(null);
        jPanel1.add(contrasenaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 312, 250, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        JFrame frame = new VentanaLogin(ois, oos, key);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonCancelarMousePressed

    private void botonRegistrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMousePressed
        //comrovamos que ha acceptado los terminos con firma digital
        if (checkTerminos.isSelected() && check) {
            try {
                //creamos pattern para que escriba la primera letra de el nombre y apellido en mayus
                int edad = Integer.parseInt(edadField.getText());
                Pattern mayus = Pattern.compile("^([A-Z]{1}[a-z]+)$");
                if (!nombreField.getText().isBlank() && !apellidoField.getText().isBlank() && !emailField.getText().isBlank() && !usuarioField.getText().isBlank() && !contrasenaField.getText().isBlank()) {
                    Matcher nombre = mayus.matcher(nombreField.getText());
                    Matcher apellido = mayus.matcher(apellidoField.getText());
                    if (nombre.find() && apellido.find()) {
                        //duda preguntar
                        Pattern edadp = Pattern.compile("^[0-9]{1,3}$");
                        Matcher edadmatch = edadp.matcher(edadField.getText());
                        if (edadmatch.find()) {
                            //enviamos la opcion escogida
                            oos.writeObject(2);
                            //creamos un objeto con todos los datos para registrase
                            MessageDigest md = MessageDigest.getInstance("SHA");
                            byte[] contrasenaBytes = contrasenaField.getText().getBytes();
                            md.update(contrasenaBytes);
                            byte[] resumen = md.digest();
                            String hashContrasena = new String(resumen);
                            NuevoUsuario registrarse = new NuevoUsuario(nombreField.getText(), apellidoField.getText(), edad, emailField.getText(), usuarioField.getText(), hashContrasena);
                            ByteArrayOutputStream bos = new ByteArrayOutputStream();
                            ObjectOutputStream oosbytes = new ObjectOutputStream(bos);
                            //lo comvertimos a bytes
                            oosbytes.writeObject(registrarse);
                            oosbytes.flush();
                            byte[] registrarsebytes = bos.toByteArray();
                            Cipher desCipher = Cipher.getInstance("DES");
                            //configuramos modo descifrar
                            desCipher.init(Cipher.ENCRYPT_MODE, key);
                            byte[] registrarseCifrado = desCipher.doFinal(registrarsebytes);
                            //enviamos objeto cifrado
                            oos.writeObject(registrarseCifrado);
                            JOptionPane.showMessageDialog(null, "El usuario se ha creado correctamente.");
                            JFrame frame = new VentanaLogin(ois, oos, key);
                            frame.setVisible(true);
                            dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Los datos del campo edad no son correctos.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Comprueba que el nombre y apellido esta bien escrito.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos para registrarse.");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Los datos del campo de edad no son validos.");
            } catch (NoSuchPaddingException | BadPaddingException | IllegalBlockSizeException | IOException ex) {
                JOptionPane.showMessageDialog(null, "ERROR inesperado.");
            } catch (NoSuchAlgorithmException ex) {
                JOptionPane.showMessageDialog(null, "No se ha especificado el algoritmo.");
            } catch (InvalidKeyException ex) {
                JOptionPane.showMessageDialog(null, "La llave no es la correcta.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tienes que aceptar los terminos para poder crear una nueva cuenta.");
        }
    }//GEN-LAST:event_botonRegistrarseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoField;
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JPanel botonRegistrarse;
    private javax.swing.JCheckBox checkTerminos;
    private javax.swing.JPasswordField contrasenaField;
    private javax.swing.JTextField edadField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
